name: noticias oficina burman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61258
title: Noticias Oficina Burman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b48e3f'
    - '#6e512d'
    - '#dac597'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
