name: oficinaburman
favicon: null
layout_spectrum: 0.75358
typography_spectrum: 0.455637130420655
title: Oficina Burman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b48e3f'
    - '#6e512d'
    - '#dac597'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
